#!/bin/sh
# Find the slackware directory in a mounted iso

# Override by setting SLACKPATH in the environment
[ -z "$SLACKPATH" ] || { echo $SLACKPATH; exit 0; }

[ $# -eq 0 ] || { echo "$0 takes no arguments" 1>&2;exit 1; }
SLACKREV=$(cat /etc/slackware-version|cut -f2 -d' ')
[ $(uname -m) = x86_64 ] && ARCHSUFFIX="64" || ARCHSUFFIX=""
m=$(mount | grep -E slackware$ARCHSUFFIX-$SLACKREV-install-dvd.iso |
  cut -f3 -d' ')
[ -n "$m" ] && echo $m/slackware$ARCHSUFFIX || echo NONE
